# Generated by Django 3.0.4 on 2020-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='location',
        ),
        migrations.AddField(
            model_name='institution',
            name='population',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
