# Generated by Django 3.0.4 on 2020-05-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200514_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='head',
            old_name='name',
            new_name='principle',
        ),
    ]
