# Generated by Django 3.0.4 on 2020-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200514_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='head',
            old_name='principle',
            new_name='principal',
        ),
    ]
