SERVICE_CHOICES = (
    (u'Kenya Army', u'Kenya Army'),
    (u'Air Force', u'Air Force'),
    (u'Navy', u'Navy'),
    (u'Training Schools', u'Training Schools')
)

UNIT_CHOICES = (
    (u'HQ KA', u'HQ KA'),
    (u'DOD CAU', u'DOD CAU'),
    (u'1 KR', u'1 KR'),
    (u'3 KR', u'3 KR'),
    (u'5 KR', u'5 KR'),
    (u'7 KR', u'7 KR'),
    (u'9 KR', u'9 KR'),
    (u'78 TK BN', u'78 TK BN'),
    (u'81 TK BN', u'81 TK BN'),
    (u'ART Brigade', u'ART Brigade'),
    (u'Ranger', u'Ranger'),
    (u'SF', u'SF'),
    (u'Brigade HQ', u'Brigade HQ'),
    (u'ENG Brigade', u'ENG Brigade'),
    (u'Base', u'Base'),
    (u'ADU', u''),
    (u'Masura Sation', u'Masura Sation'),
    (u'KMA', u'KMA'),
    (u'RTS', u'RTS'),
    (u'SOI', u'SOI'),
    (u'NTS', u'NTS'),
    (u'DEFTEC', u'DEFTEC'),
)

RANK_CHOICES = (
    (u'Gen', u'General'),
    (u'DOD CAU', u'Leutanant General'),
    (u'Maj Gen', u'Major General'),
    (u'Brig', u'Brigedia'),
    (u'Col', u'Colonel'),
    (u'LT Col', u'Leutenant Colonel'),
    (u'Maj', u'Major'),
    (u'Capt', u'Captain'),
    (u'LT', u'Leutanant'),
    (u'2LT', u'Second Leutanant'),
    (u'WOI', u'Warrant Officer I'),
    (u'WOII', u'Warrant Officer II'),
    (u'SSGT', u'Senior Sergent'),
    (u'SGT', u'Sergent'),
    (u'CPL', u'Coprol'),
    (u'PTE', u'Private'),
)
